fix import error
Fix this error:

> ImportError: cannot import name 'url_encode' from 'werkzeug.urls' (/usr/local/lib/python3.12/site-packages/werkzeug/urls.py)

Need a slightly newer version of flask-wtf, since werkzeugh 3+ doesn't include that anymore.